config/routes.rb
Rails.application.routes.draw do
  get 'favorite_books/create'
  get 'favorite_books/destroy'
  get 'mycomments' => 'comments#index'

  devise_for :users
  get 'catalog' => 'static_pages#catalog'
  root 'static_pages#home'
  resources :users, only: [:show]
  resources :books, only: [:show, :new, :create] do
    resources :comments, only:[:create, :edit, :destroy, :update]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    validates :name, length: { maximum: 20}, presence: true
    validates :second_name, length: { maximum: 20}, presence: true
    validates :middle_name, length: { maximum: 20}, presence: true

    has_many :books, dependent: :destroy

    def getFioAuthor
      "#{second_name} #{name[0]}. #{middle_name[0]}."
    end
end

app/models/book.rb
class Book < ApplicationRecord
    validates :name, length: {maximum: 30}, presence: true
    validates :description, length: {maximum: 200}, presence: true
    belongs_to :author
    mount_uploader :book_cover, PictureUploader

    has_many :comments,dependent: :destroy
    has_many :commentators, through: :comments, foreign_key: "book_id", source: :user

    has_many :favorite_books,dependent: :destroy
    has_many :fans, through: :favorite_books, source: :user
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :book

    validates :text, length: {maximum: 100}, presence: true
end

app/models/favorite_book.rb
class FavoriteBook < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable
  validates :name, length: {maximum: 20}, presence: true
  validates :second_name, length: {maximum: 20}, presence: true
  validates :middle_name, length: {maximum: 20}, presence: true
  validates :avatar, presence: true
  mount_uploader :avatar, PictureUploader

  has_many :comments,dependent: :destroy
  has_many :commented_books, through: :comments, foreign_key:"user_id", source: :book

  has_many :favorite_books,dependent: :destroy
  has_many :liked_books, through: :favorite_books, source: :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [:name, :second_name, :middle_name,:avatar])
    devise_parameter_sanitizer.permit(:account_update,keys: [:name, :second_name, :middle_name,:avatar])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!, only:[:show,:new, :create]
    before_action :admin_check, only:[:new, :create]
    def show
        @book = Book.find(params[:id])
        @comment = @book.comments.new
    end
    def new
        @book = Book.new
        @authors = Author.all.map {|author| [author.getFioAuthor,author.id]}
    end
    def create
        #byebug
        @book = Book.new(book_params)
        render action: :new unless @book.save
        redirect_back book_url(@book)
    end
    private

    def book_params
        params.require(:book).permit(:name,:author_id, :book_cover, :description)
    end
    def admin_check
        redirect_to root_url if current_user.admin
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!, only: [:create, :edit,:update,:destroy,:index]
    before_action :admin_check, only: [:create]
    before_action :checkCommentOwner, only:[:update,:destroy,:edit]
    def create
      if Book.find(params[:book_id]).comments.create(user_id: current_user.id,text: params[:comment][:text],is_moderate: false)
        flash[:notice] = "Комментарий создан"
      end
        redirect_back fallback_location: root_url
    end
    def edit
        @comment = Comment.find(params[:id])
        @is_edit = true
    end
    def update
        comment = Book.find(params[:book_id]).comments.find(params[:id])
        is_mod = params[:comment].nil? ? false : params[:comment][:is_moderate]
        byebug
        if comment.update_attributes(text: params[:comment][:text], is_moderate: is_mod)
            flash[:notice] = "Комментарий сохранен"
        else
            flash[:alert] = "Произошла ошибка"
            render action: :edit
        end

        redirect_back fallback_location: root_url

    end
    def destroy
        if Book.find(params[:book_id]).comments.find(params[:id]).destroy
             flash[:notice] = "Комментарий удален"
        else
            flash[:alert] = "Произошла ошибка"
        end
        redirect_back fallback_location: root_url
    end

    def index
        if current_user.admin?
            @comments = Comment.all
        else
            @comments = current_user.comments
        end
        @comments = @comments.paginate(page:params[:page], per_page:10)
    end

    private


    def admin_check
      redirect_to root_url if current_user.admin?
    end
    def getCommentStatus
      current_user.admin ? params[:comment][:is_moderate] : false
    end
    def checkCommentOwner
      redirect_to root_url if !current_user.comments.include?(Comment.find(params[:id])) && !current_user.admin?
    end
end

app/controllers/favorite_books_controller.rb
class FavoriteBooksController < ApplicationController
  before_action :authenticate_user!, only:[:create, :destroy]
  def create
    book = current_user.favorite_books.new(book_id:params[:format])

    flash[:notice] = "Книга добавлена" if book.save
    redirect_to catalog_url
  end

  def destroy
    #byebug
    book = current_user.favorite_books.find_by(book_id: params[:format])
    flash[:notice] = "Книга удалена" if book.destroy
    redirect_back fallback_location: root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:catalog]
  def home
  end

  def catalog
    @books = Book.paginate(page: params[:page], per_page: 20)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
        @favorite_books = @user.liked_books.paginate(page: params[:page], per_page: 10)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/books_helper.rb
module BooksHelper
  def correct_user_for_comments?
    !current_user.nil? && !current_user.admin?
  end
  def valid_book_for_add?(book)
    current_page?(catalog_url) && user_signed_in? && !FavoriteBook.where(user_id: current_user.id, book_id: book.id).exists?

  end
  def valid_book_for_remove?(book)
    !current_user.nil? && FavoriteBook.where(user_id: current_user.id, book_id: book.id).exists?

  end
  def getFullNameBook(book)
    "#{book.author.second_name} #{book.author.name[0]}. #{book.author.middle_name[0]}. - #{book.name}"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def correct_user?(comment)
    user_signed_in? && (comment.user.id == current_user.id || current_user.admin)
  end
  def getCommentStatus(comment)
    !comment.is_moderate ? "unmoderate" : "moderate"
  end
  def getFIOAuthor(comment)
    "#{comment.user.second_name} #{comment.user.name}"
  end
end

app/helpers/favorite_books_helper.rb
module FavoriteBooksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def correct_admin_user?
    !current_user.nil? && current_user.admin
  end
  def correct_user?(comment)
    user_signed_in? && (comment.user.id == current_user.id || current_user.admin)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/books/_book.html.erb
<div class="book_item" id="book-<%=book.id%>">
    <div class="image_part"><%= image_tag book.book_cover.url%></div>
    <div class="text_path"><%=link_to getFullNameBook(book), book_url(book.id)%></div>
    <% if valid_book_for_add?(book) %>
        <%=link_to "Добавить",  favorite_books_create_url(book.id)%>
    <%end%>
    <% if valid_book_for_remove?(book)%>
        <%=link_to "Удалить",  favorite_books_destroy_url(book.id)%>
    <%end%>
</div>

app/views/books/_new_form.html.erb
<%= form_for @book,:html => {:multipart => true} do |f|%>
    <div class="form-group">
        <%= f.label :name, "Название"%>
        <%= f.text_field :name %>
    </div>

    <div class="form-group">
        <%= f.label :description, "Описание"%>
        <%= f.text_area :description, size: "60x12"%>
    </div>

    <div class="form-group">
        <%= f.label :author_id, "Автор"%>
        <%= f.select :author_id, options_for_select(@authors)%>
    </div>
    <div class="form-group">
        <%= f.label :book_cover, "Обложка"%>
        <%= f.file_field :book_cover %>
    </div>
    <%= f.submit "Отправить" %>
<%end%>

app/views/books/create.js.erb
$('tr#book_<%= @book.id %>').replaceWith("<%= escape_javascript(render @book) %>")
$.lazybox.close()

app/views/books/new.js.erb
$.lazybox("<%= j(render :partial => 'new_form') %>", {klass: 'custom'});

app/views/books/show.html.erb
<% provide(:title,"#{@book.author.second_name} #{@book.author.name[0]}. #{@book.author.middle_name[0]}. - #{@book.name}")%>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4">
            <%= image_tag  @book.book_cover.url%>
        </div>
        <div class="col-md-8">
            <h2 class="h2">Название: <%= @book.name%></h2>
            <h2 class="h2">Автор: <%= "#{@book.author.second_name} #{@book.author.name} #{@book.author.middle_name}"%></h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <h2 class="h2 text-center">Описание</h2>
            <p class="text-justify"> <%= @book.description%></p>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
  <div class="container-fluid">
      <h2 class="text-center">Отзывы</h2>
      <%= render @book.comments.select {|c| c.is_moderate == true}%>
      <%= render 'comments/comment_form' if correct_user_for_comments?%>
  </div>

app/views/comments/_comment.html.erb
<div class="row">
    <div class="col-md-4">

    </div>
    <div class="col-md-4 comment_body <%=getCommentStatus(comment)%>" id="comment_<%=comment.id%>">
        <p class="author"><%= getFIOAuthor(comment)%></p>
        <p class="text"><%= comment.text%></p>
        <%if correct_user?(comment)%>
            <%= link_to 'Изменить', edit_book_comment_path(id: comment.id, book_id: comment.book_id), remote:true%>
            <%= link_to 'Удалить',book_comment_path(id:comment.id, book_id: comment.book_id), method: :delete%>
        <%end%>
    </div>
    <div class="col-md-4">

    </div>
</div>

app/views/comments/_comment_form.html.erb
<div class="row">
    <div class="col-md-4">

    </div>
    <div class="col-md-4">
      <%if @is_edit%>
        <%= form_for @comment, url:book_comment_path(book_id:@comment.book_id,id:@comment.id), method: "put" do |f|%>
            <div class="form-group">
                <%= f.label :text, "Оставить отзыв"%><br>
                <%= f.text_area(:text, size: "70x6") %>
            </div>
            <%if current_user.admin%>
                <div class="form-group">
                    <%=f.label :is_moderate, "Отзыв корректен?"%>
                    <%=f.check_box :is_moderate%>
                </div>
            <%end%>
            <div class="form-group">
                <%= hidden_field_tag(:id, params[:id]) %>
                <%= f.submit "Подтвердить" %>
            </div>
        <%end%>
      <%else%>
            <%= form_for @comment, url:book_comments_path(book_id: @book.id), method: "create" do |f|%>
            <div class="form-group">
                <%= f.label :text, "Оставить отзыв"%><br>
                <%= f.text_area(:text, size: "70x6") %>
            </div>
            <%if current_user.admin%>
                <div class="form-group">
                    <%=f.label :is_moderate, "Отзыв корректен?"%>
                    <%=f.check_box :is_moderate%>
                </div>
            <%end%>
            <div class="form-group">
                <%= hidden_field_tag(:id, params[:id]) %>
                <%= f.submit "Подтвердить" %>
            </div>
        <%end%>
      <%end%>


    </div>
    <div class="col-md-4">

    </div>
</div>

app/views/comments/edit.js.erb
$.lazybox("<%= j(render :partial => 'comment_form') %>", {klass: 'custom'});

app/views/comments/index.html.erb
<%provide(:title,"Мои отзывы")%>
<div class="container-fluid">
    <div class="row">
        <h1 class="h1 text-center">Мои отзывы</h1>
    </div>
    <%= will_paginate @comments %>
    <div class="row">
        <%=render @comments%>
    </div>
</div>

app/views/comments/update.js.erb
$('tr#comment_<%= @comment.id %>').replaceWith("<%= escape_javascript(render @comment) %>")
$.lazybox.close()

app/views/favorite_books/new.html.erb
<h1>FavoriteBooks#new</h1>
<p>Find me in app/views/favorite_books/new.html.erb</p>

app/views/layouts/_footer.html.erb
<section id="footer">
		<div class="container">
			<div class="row text-center text-xs-center text-sm-left text-md-left" id="wrapper">
				<div class="col-xs-12 col-sm-4 col-md-4" id="links">
					<h5>Quick links</h5>
					<ul class="list-unstyled quick-links">
						<li><a href="<%= root_url%>"><i class="fa fa-angle-double-right"></i>Главная</a></li>
						<li><a href="<%= catalog_url%>"><i class="fa fa-angle-double-right"></i>Каталог</a></li>
					</ul>
				</div>
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
					<p>National Transaction Corporation is a Registered MSP/ISO of Elavon, Inc. Georgia [a wholly owned subsidiary of U.S. Bancorp, Minneapolis, MN]</p>
					<p class="h6">&copy All right Reversed.<a class="text-green ml-2" href="https://www.sunlimetech.com" target="_blank">Sunlimetech</a></p>
				</div>
				</hr>
			</div>	
		</div>
	</section>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation"> 
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
            data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<%= root_url %>">MyBooks</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><%= link_to "Главная",root_url%></li>
                <li><%= link_to "Каталог",catalog_url if user_signed_in?%></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            <% if !user_signed_in?%>
                <li><%= link_to 'Войти', new_user_session_path%></li>
                <li><%= link_to 'Зарегистрироваться', new_user_registration_path%></li>
                
            <%else%>
                <li><%= link_to 'Профиль', user_path(current_user) %></li>
                <li><%= link_to 'Мои отзывы', mycomments_url%></li>
                
                <li><%= link_to 'Выйти', destroy_user_session_path, :method => :delete%></li>
            <%end%>
                
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title)%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <header>
        <%= render 'layouts/header'%>
      </header>
      <div id="content">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= render_lazybox%>
        <%= yield %>
      </div>
      <footer>
        <%= render 'layouts/footer'%>
      </footer>
    </div>
  </body>
</html>

app/views/static_pages/catalog.html.erb
<%provide(:title, "Каталог")%>
<h1 class='h1 text-center'>Каталог</h1>
<p class='lead text-center'>
    Здесь вы найдете книги на свой вкус.<br>
    <%= link_to "Добавить", new_book_url, remote: true if correct_admin_user?%>
</p>
<%= will_paginate @books%>
<div id="catalog">
    <%= render @books%>
</div>

app/views/static_pages/home.html.erb
<%provide(:title, "Главная")%>
<h1 class="h1 text-center">Добро пожаловать на сайт MyBooks</h1>
<p class="lead text-center">
    На нашем сайте вы найжете множество книг, которые придутся вам по вкусу.
    <%if !user_signed_in?%>
        Если вы еще не зарегистрировались, пожалуйста, перейдите по ссылке <%=link_to 'Зарегистрироваться',new_user_registration_path%>.
    <%end%>
</p>
<%if !user_signed_in?%>
    <p class="lead text-center">
        Если вы уже зарегистрированы на сайте, вы можете войти на сайт, перейдя по ссылке <%=link_to 'Войти', new_user_session_path%>.
    </p>
<%end%>

app/views/users/show.html.erb
<%provide(:title, "Профиль")%>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4"> 
            
            <%= image_tag @user.avatar.thumb.url, id:"avatar_field" %>
            
        </div>
        <div class="col-md-6" id="user_info">
            <h2> Фамилия: <%= @user.second_name%></p>
            <h2> Имя: <%= @user.name%></p>
            <h2> Отчество: <%= @user.middle_name%></p>
            <%= link_to "Изменить", edit_user_registration_url(@user)%>
        </div>
    </div>
    <% if user_signed_in? && current_user.id == @user.id%>
    <div class="row text-center">
        <h2>Любимые книги</h2>
        <%= will_paginate @favorite_books%>
        <div class="col-md-2">

        </div>
        <div class="col-md-8" id="favourite_book_field">
            <%=render @favorite_books%>
        </div>
        <div class="col-md-2">

        </div>
    </div>  
    <%end%> 
</div>